### ISSUE TITLE
failed: sysctl: cannot stat /proc/sys/net/bridge/bridge-nf-call-iptables: No such file or directory

### ISSUE THREAD

**Issue by aaronpkelly** [rak8s/rak8s#13]
I got the following failure on this task:

``
TASK [common : Pass bridged IPv4 traffic to iptables' chains] ******************
fatal: [black]: FAILED! => {"changed": false, "failed": true, "msg": "setting net.bridge.bridge-nf-call-iptables failed: sysctl: cannot stat /proc/sys/net/bridge/bridge-nf-call-iptables: No such file or directory\n"}
``

To fix, I had to ssh to each of my nodes and run the following commands:
``
sudo modprobe br_netfilter
sudo sysctl -p
``

The ansible playbook would then proceed

**Comment by LoganAvatar** [comment]
I had this same issue, re-running the playbook a 2nd time succeeded ... its not a fix, but it is a workaround.

**Comment by premkumar-masilamani** [comment]
It did work for me too. But, I don't understand why it would work the second time.  :(

**Comment by premkumar-masilamani** [comment]
Hi @aaronpkelly - Could you please close this issue?
