### ISSUE TITLE
pod-network-cidr not correct for flannel

### ISSUE THREAD

**Issue by martinborgman** [rak8s/rak8s#42]
## OS running on Ansible host:
Raspbian 9.4

## Ansible Version (`ansible --version`):
2.7.1

## Raspberry Pi Hardware Version:
3 Model B

## Raspberry Pi OS & Version (`cat /etc/os-release`):
Raspbian lite 9.4

# Detailed description of the issue:
A container running blinkt-k8s-controller was unable to access the kubernetes API server on 10.96.0.1.

This was caused by a incorrect pod-network-cidr in roles/master/tasks/main.yml. The correct pod-network-cidr for flannel is 10.244.0.0/16.

**Comment by chris-short** [comment]
I'm not sure where you're getting 10.96.0.1 from. The podnet variable is set to 10.244.0.0/16: https://github.com/rak8s/rak8s/blob/9031d74fea51ba15d9c91d529eca230ebc59ab0b/group_vars/all.yml#L2

**Comment by martinborgman** [comment]
Please look in roles/master/tasks/main.yml. The kubeadm init command doesn't use the podnet variable.

**Comment by chris-short** [comment]
Please check the latest release: https://github.com/rak8s/rak8s/releases/tag/v0.2.2
