### ISSUE TITLE
Unable to Initialize master due to docker version

### ISSUE THREAD

**Issue by jaevans** [rak8s/rak8s#43]
## OS running on Ansible host:
Mac OS 10.14.1 (Mojave)

## Ansible Version (`ansible --version`):
ansible 2.7.2 (homebrew)

## Raspberry Pi Hardware Version:
3B, 3B+

## Raspberry Pi OS & Version (`cat /etc/os-release`):

PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
NAME="Raspbian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

# Detailed description of the issue:

When installing, `roles/kubeadm/tasks/main.yml` installs docker-ce (version 18.04.0~ce~3-0~raspbian), which installs `/etc/apt/sources.list.d/docker.list`. If the process hangs, hits a hiccup, or for whatever reason needs to be restarted, an apt-get upgrade is called, which bumps docker to the latest version. The pre-flight for `kubeadm init` then fails due to unsupported docker version.

**Comment by chris-short** [comment]
Thank you, @jaevans!
