### ISSUE TITLE
Patch K8S Vulnerability

### ISSUE THREAD

**Issue by jimhopkinsjr** [rak8s/rak8s#50]
## OS running on Ansible host:
```
NAME="Ubuntu"
VERSION="16.04.5 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.5 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```

## Ansible Version (`ansible --version`):
```
ansible 2.5.5
  config file = /media/psf/Home/git/personal/raspk8s/ansible.cfg
  configured module search path = [u'/home/jim/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.12 (default, Nov 12 2018, 14:36:49) [GCC 5.4.0 20160609]
```
## Raspberry Pi Hardware Version:
ANY
## Raspberry Pi OS & Version (`cat /etc/os-release`):
Any
# Detailed description of the issue:

K8S has a vulnerability in the version that is pinned in `groupvar/all.yml`:
https://github.com/rak8s/rak8s/blob/ecbfe7ad387873f26e9a5d7f0d51c5f4e9e3d7e9/group_vars/all.yml#L15

https://github.com/kubernetes/kubernetes/issues/71411 - K8S Issue

K8S has patched this vulnerability in:
```
v1.10.11
v1.11.5
v1.12.3
v1.13.0+
```

**Comment by chris-short** [comment]
Patched a while ago. Sorry I didn't see this sooner.
